# Generated by Django 3.0.8 on 2021-09-25 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=30, null=True)),
                ('txn_id', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('amount_initiated', models.FloatField(blank=True, null=True)),
                ('was_success', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('log', models.TextField(blank=True, null=True)),
                ('registered_for', models.TextField(blank=True, null=True)),
                ('txn_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('ru_date', models.DateTimeField(blank=True, null=True)),
                ('s2s_date', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
